export const DemoErr = {
  DEMO_SECTION_MISSING: 'E_DEMO_SECTION_MISSING',
  NO_O_ROWS: 'E_NO_O_ROWS',
  ROW_CLICK_MISSING: 'E_ROW_CLICK_MISSING',
  ORDER_TIMEOUT: 'E_ORDER_TIMEOUT',
  PANEL_TIMEOUT: 'E_PANEL_TIMEOUT',
  VIEW_FN_MISSING: 'E_VIEW_FN_MISSING',
};
